# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.
include: "rules/common.smk"
include: "rules/all_input.smk"
include: "rules/simple_example.smk"


rule all:
    input:
        all_input,
